# Generated by Django 3.2.9 on 2021-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('pk_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=4)),
                ('aspect_ratio', models.CharField(max_length=2)),
                ('wheel_size', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_actvate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tires',
            },
        ),
    ]
