# Generated by Django 3.2.9 on 2021-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='aspect_ratio',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tire',
            name='wheel_size',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tire',
            name='width',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
